export interface Move {
  name: string;
  type: string;
  power: number;
  accuracy: number;
  pp: number;
}

export interface PokemonSkills {
  [pokemonName: string]: Move[];
}

export const pokemonSkills: PokemonSkills = {
  Bulbasaur: [
    { name: "Tackle", type: "Normal", power: 40, accuracy: 100, pp: 8 },
    { name: "Vine Whip", type: "Grass", power: 45, accuracy: 100, pp: 5 },
    { name: "Growl", type: "Normal", power: 0, accuracy: 100, pp: 4 },
    { name: "Leech Seed", type: "Grass", power: 0, accuracy: 90, pp: 3 },
  ],
  Ivysaur: [
    { name: "Tackle", type: "Normal", power: 40, accuracy: 100, pp: 8 },
    { name: "Vine Whip", type: "Grass", power: 45, accuracy: 100, pp: 6 },
    { name: "Razor Leaf", type: "Grass", power: 55, accuracy: 95, pp: 5 },
    { name: "Sleep Powder", type: "Grass", power: 0, accuracy: 75, pp: 3 },
  ],
  Venusaur: [
    { name: "Razor Leaf", type: "Grass", power: 55, accuracy: 95, pp: 6 },
    { name: "Vine Whip", type: "Grass", power: 45, accuracy: 100, pp: 6 },
    { name: "Earthquake", type: "Ground", power: 100, accuracy: 100, pp: 2 },
    { name: "Solar Beam", type: "Grass", power: 120, accuracy: 100, pp: 1 },
  ],
  Charmander: [
    { name: "Scratch", type: "Normal", power: 40, accuracy: 100, pp: 8 },
    { name: "Ember", type: "Fire", power: 40, accuracy: 100, pp: 6 },
    { name: "Growl", type: "Normal", power: 0, accuracy: 100, pp: 4 },
    { name: "Smokescreen", type: "Normal", power: 0, accuracy: 100, pp: 4 },
  ],
  Charmeleon: [
    { name: "Flamethrower", type: "Fire", power: 90, accuracy: 100, pp: 3 },
    { name: "Slash", type: "Normal", power: 70, accuracy: 100, pp: 5 },
    { name: "Fire Fang", type: "Fire", power: 65, accuracy: 95, pp: 5 },
    { name: "Smokescreen", type: "Normal", power: 0, accuracy: 100, pp: 4 },
  ],
  Charizard: [
    { name: "Flamethrower", type: "Fire", power: 90, accuracy: 100, pp: 4 },
    { name: "Wing Attack", type: "Flying", power: 60, accuracy: 100, pp: 6 },
    { name: "Fire Spin", type: "Fire", power: 35, accuracy: 85, pp: 5 },
    { name: "Slash", type: "Normal", power: 70, accuracy: 100, pp: 5 },
  ],
  Squirtle: [
    { name: "Tackle", type: "Normal", power: 40, accuracy: 100, pp: 8 },
    { name: "Water Gun", type: "Water", power: 40, accuracy: 100, pp: 6 },
    { name: "Tail Whip", type: "Normal", power: 0, accuracy: 100, pp: 4 },
    { name: "Bubble", type: "Water", power: 40, accuracy: 100, pp: 6 },
  ],
  Wartortle: [
    { name: "Water Gun", type: "Water", power: 40, accuracy: 100, pp: 6 },
    { name: "Bite", type: "Dark", power: 60, accuracy: 100, pp: 5 },
    { name: "Rapid Spin", type: "Normal", power: 50, accuracy: 100, pp: 5 },
    { name: "Protect", type: "Normal", power: 0, accuracy: 100, pp: 3 },
  ],
  Blastoise: [
    { name: "Hydro Pump", type: "Water", power: 110, accuracy: 80, pp: 2 },
    { name: "Surf", type: "Water", power: 90, accuracy: 100, pp: 3 },
    { name: "Bite", type: "Dark", power: 60, accuracy: 100, pp: 5 },
    { name: "Skull Bash", type: "Normal", power: 130, accuracy: 100, pp: 1 },
  ],
  Caterpie: [
    { name: "Tackle", type: "Normal", power: 40, accuracy: 100, pp: 8 },
    { name: "String Shot", type: "Bug", power: 0, accuracy: 95, pp: 4 },
    { name: "Bug Bite", type: "Bug", power: 60, accuracy: 100, pp: 5 },
    { name: "Harden", type: "Normal", power: 0, accuracy: 100, pp: 5 },
  ],
  Metapod: [
    { name: "Harden", type: "Normal", power: 0, accuracy: 100, pp: 6 },
    { name: "Tackle", type: "Normal", power: 40, accuracy: 100, pp: 8 },
    { name: "Bug Bite", type: "Bug", power: 60, accuracy: 100, pp: 5 },
    { name: "String Shot", type: "Bug", power: 0, accuracy: 95, pp: 4 },
  ],
  Butterfree: [
    { name: "Confusion", type: "Psychic", power: 50, accuracy: 100, pp: 5 },
    { name: "Gust", type: "Flying", power: 40, accuracy: 100, pp: 6 },
    { name: "Stun Spore", type: "Grass", power: 0, accuracy: 75, pp: 4 },
    { name: "Sleep Powder", type: "Grass", power: 0, accuracy: 75, pp: 3 },
  ],
  Weedle: [
    { name: "Poison Sting", type: "Poison", power: 15, accuracy: 100, pp: 8 },
    { name: "String Shot", type: "Bug", power: 0, accuracy: 95, pp: 4 },
    { name: "Bug Bite", type: "Bug", power: 60, accuracy: 100, pp: 5 },
    { name: "Harden", type: "Normal", power: 0, accuracy: 100, pp: 4 },
  ],
  Kakuna: [
    { name: "Harden", type: "Normal", power: 0, accuracy: 100, pp: 6 },
    { name: "Poison Sting", type: "Poison", power: 15, accuracy: 100, pp: 7 },
    { name: "Bug Bite", type: "Bug", power: 60, accuracy: 100, pp: 5 },
    { name: "String Shot", type: "Bug", power: 0, accuracy: 95, pp: 4 },
  ],
  Beedrill: [
    { name: "Twineedle", type: "Bug", power: 25, accuracy: 100, pp: 6 },
    { name: "Poison Sting", type: "Poison", power: 15, accuracy: 100, pp: 8 },
    { name: "Fury Attack", type: "Normal", power: 15, accuracy: 85, pp: 6 },
    { name: "Agility", type: "Psychic", power: 0, accuracy: 100, pp: 3 },
  ],
  Pidgey: [
    { name: "Tackle", type: "Normal", power: 40, accuracy: 100, pp: 8 },
    { name: "Gust", type: "Flying", power: 40, accuracy: 100, pp: 6 },
    { name: "Sand Attack", type: "Ground", power: 0, accuracy: 100, pp: 4 },
    { name: "Quick Attack", type: "Normal", power: 40, accuracy: 100, pp: 6 },
  ],
  Pidgeotto: [
    { name: "Wing Attack", type: "Flying", power: 60, accuracy: 100, pp: 6 },
    { name: "Quick Attack", type: "Normal", power: 40, accuracy: 100, pp: 6 },
    { name: "Agility", type: "Psychic", power: 0, accuracy: 100, pp: 3 },
    { name: "Sand Attack", type: "Ground", power: 0, accuracy: 100, pp: 4 },
  ],
  Pidgeot: [
    { name: "Wing Attack", type: "Flying", power: 60, accuracy: 100, pp: 6 },
    { name: "Quick Attack", type: "Normal", power: 40, accuracy: 100, pp: 6 },
    { name: "Agility", type: "Psychic", power: 0, accuracy: 100, pp: 3 },
    { name: "Feather Dance", type: "Flying", power: 0, accuracy: 100, pp: 5 },
  ],
  Rattata: [
    { name: "Tackle", type: "Normal", power: 40, accuracy: 100, pp: 8 },
    { name: "Quick Attack", type: "Normal", power: 40, accuracy: 100, pp: 6 },
    { name: "Bite", type: "Dark", power: 60, accuracy: 100, pp: 5 },
    { name: "Focus Energy", type: "Normal", power: 0, accuracy: 100, pp: 3 },
  ],
  Raticate: [
    { name: "Bite", type: "Dark", power: 60, accuracy: 100, pp: 5 },
    { name: "Hyper Fang", type: "Normal", power: 80, accuracy: 90, pp: 5 },
    { name: "Quick Attack", type: "Normal", power: 40, accuracy: 100, pp: 6 },
    { name: "Tail Whip", type: "Normal", power: 0, accuracy: 100, pp: 4 },
  ],
  Spearow: [
    { name: "Peck", type: "Flying", power: 35, accuracy: 100, pp: 6 },
    { name: "Fury Attack", type: "Normal", power: 15, accuracy: 85, pp: 6 },
    { name: "Leer", type: "Normal", power: 0, accuracy: 100, pp: 4 },
    { name: "Agility", type: "Psychic", power: 0, accuracy: 100, pp: 3 },
  ],
  Fearow: [
    { name: "Drill Peck", type: "Flying", power: 80, accuracy: 100, pp: 5 },
    { name: "Agility", type: "Psychic", power: 0, accuracy: 100, pp: 3 },
    { name: "Fury Attack", type: "Normal", power: 15, accuracy: 85, pp: 6 },
    { name: "Leer", type: "Normal", power: 0, accuracy: 100, pp: 4 },
  ],
  Ekans: [
    { name: "Wrap", type: "Normal", power: 15, accuracy: 90, pp: 5 },
    { name: "Bite", type: "Dark", power: 60, accuracy: 100, pp: 5 },
    { name: "Glare", type: "Normal", power: 0, accuracy: 100, pp: 5 },
    { name: "Poison Fang", type: "Poison", power: 50, accuracy: 100, pp: 5 },
  ],
  Arbok: [
    { name: "Acid", type: "Poison", power: 40, accuracy: 100, pp: 6 },
    { name: "Bite", type: "Dark", power: 60, accuracy: 100, pp: 5 },
    { name: "Glare", type: "Normal", power: 0, accuracy: 100, pp: 5 },
    { name: "Poison Fang", type: "Poison", power: 50, accuracy: 100, pp: 5 },
  ],
  Pikachu: [
    {
      name: "Thunder Shock",
      type: "Electric",
      power: 40,
      accuracy: 100,
      pp: 6,
    },
    { name: "Quick Attack", type: "Normal", power: 40, accuracy: 100, pp: 6 },
    { name: "Thunder Wave", type: "Electric", power: 0, accuracy: 90, pp: 10 },
    { name: "Electro Ball", type: "Electric", power: 60, accuracy: 100, pp: 6 },
  ],
  Sandshrew: [
    { name: "Scratch", type: "Normal", power: 40, accuracy: 100, pp: 8 },
    { name: "Sand Attack", type: "Ground", power: 0, accuracy: 100, pp: 4 },
    { name: "Poison Sting", type: "Poison", power: 15, accuracy: 100, pp: 8 },
    { name: "Slash", type: "Normal", power: 70, accuracy: 100, pp: 5 },
  ],
  Sandslash: [
    { name: "Slash", type: "Normal", power: 70, accuracy: 100, pp: 5 },
    { name: "Earthquake", type: "Ground", power: 100, accuracy: 100, pp: 2 },
    { name: "Poison Sting", type: "Poison", power: 15, accuracy: 100, pp: 8 },
    { name: "Sand Attack", type: "Ground", power: 0, accuracy: 100, pp: 4 },
  ],
  NidoranF: [
    { name: "Scratch", type: "Normal", power: 40, accuracy: 100, pp: 8 },
    { name: "Bite", type: "Dark", power: 60, accuracy: 100, pp: 5 },
    { name: "Poison Sting", type: "Poison", power: 15, accuracy: 100, pp: 8 },
    { name: "Double Kick", type: "Fighting", power: 30, accuracy: 100, pp: 5 },
  ],
  Nidorina: [
    { name: "Bite", type: "Dark", power: 60, accuracy: 100, pp: 5 },
    { name: "Double Kick", type: "Fighting", power: 30, accuracy: 100, pp: 5 },
    { name: "Poison Fang", type: "Poison", power: 50, accuracy: 100, pp: 5 },
    { name: "Body Slam", type: "Normal", power: 85, accuracy: 100, pp: 5 },
  ],
  Nidoqueen: [
    { name: "Earthquake", type: "Ground", power: 100, accuracy: 100, pp: 2 },
    { name: "Body Slam", type: "Normal", power: 85, accuracy: 100, pp: 5 },
    { name: "Poison Fang", type: "Poison", power: 50, accuracy: 100, pp: 5 },
    { name: "Superpower", type: "Fighting", power: 120, accuracy: 100, pp: 3 },
  ],
  NidoranM: [
    { name: "Horn Attack", type: "Normal", power: 65, accuracy: 100, pp: 5 },
    { name: "Bite", type: "Dark", power: 60, accuracy: 100, pp: 5 },
    { name: "Poison Sting", type: "Poison", power: 15, accuracy: 100, pp: 8 },
    { name: "Double Kick", type: "Fighting", power: 30, accuracy: 100, pp: 5 },
  ],
  Nidorino: [
    { name: "Horn Attack", type: "Normal", power: 65, accuracy: 100, pp: 5 },
    { name: "Poison Fang", type: "Poison", power: 50, accuracy: 100, pp: 5 },
    { name: "Double Kick", type: "Fighting", power: 30, accuracy: 100, pp: 5 },
    { name: "Bite", type: "Dark", power: 60, accuracy: 100, pp: 5 },
  ],
  Nidoking: [
    { name: "Earthquake", type: "Ground", power: 100, accuracy: 100, pp: 2 },
    { name: "Horn Attack", type: "Normal", power: 65, accuracy: 100, pp: 5 },
    { name: "Poison Jab", type: "Poison", power: 80, accuracy: 100, pp: 5 },
    { name: "Thrash", type: "Normal", power: 90, accuracy: 100, pp: 3 },
  ],
  Clefairy: [
    { name: "Pound", type: "Normal", power: 40, accuracy: 100, pp: 8 },
    { name: "Sing", type: "Normal", power: 0, accuracy: 55, pp: 3 },
    { name: "Double Slap", type: "Normal", power: 15, accuracy: 85, pp: 5 },
    { name: "Meteor Mash", type: "Steel", power: 90, accuracy: 90, pp: 5 },
  ],
  Clefable: [
    { name: "Moonblast", type: "Fairy", power: 95, accuracy: 100, pp: 5 },
    { name: "Pound", type: "Normal", power: 40, accuracy: 100, pp: 8 },
    { name: "Double Slap", type: "Normal", power: 15, accuracy: 85, pp: 5 },
    { name: "Cosmic Power", type: "Psychic", power: 0, accuracy: 100, pp: 5 },
  ],
  Vulpix: [
    { name: "Ember", type: "Fire", power: 40, accuracy: 100, pp: 6 },
    { name: "Quick Attack", type: "Normal", power: 40, accuracy: 100, pp: 6 },
    { name: "Flame Burst", type: "Fire", power: 70, accuracy: 100, pp: 5 },
    { name: "Confuse Ray", type: "Ghost", power: 0, accuracy: 100, pp: 10 },
  ],
  Ninetales: [
    { name: "Flamethrower", type: "Fire", power: 90, accuracy: 100, pp: 4 },
    { name: "Fire Spin", type: "Fire", power: 35, accuracy: 85, pp: 5 },
    { name: "Confuse Ray", type: "Ghost", power: 0, accuracy: 100, pp: 10 },
    { name: "Quick Attack", type: "Normal", power: 40, accuracy: 100, pp: 6 },
  ],
  Jigglypuff: [
    { name: "Sing", type: "Normal", power: 0, accuracy: 55, pp: 3 },
    { name: "Pound", type: "Normal", power: 40, accuracy: 100, pp: 8 },
    { name: "Double Slap", type: "Normal", power: 15, accuracy: 85, pp: 5 },
    { name: "Body Slam", type: "Normal", power: 85, accuracy: 100, pp: 5 },
  ],
  Wigglytuff: [
    { name: "Hyper Voice", type: "Normal", power: 90, accuracy: 100, pp: 10 },
    { name: "Sing", type: "Normal", power: 0, accuracy: 55, pp: 3 },
    { name: "Body Slam", type: "Normal", power: 85, accuracy: 100, pp: 5 },
    { name: "Double-Edge", type: "Normal", power: 120, accuracy: 100, pp: 3 },
  ],
  Zubat: [
    { name: "Leech Life", type: "Bug", power: 80, accuracy: 100, pp: 5 },
    { name: "Bite", type: "Dark", power: 60, accuracy: 100, pp: 5 },
    { name: "Wing Attack", type: "Flying", power: 60, accuracy: 100, pp: 6 },
    { name: "Supersonic", type: "Normal", power: 0, accuracy: 55, pp: 5 },
  ],
  Golbat: [
    { name: "Air Cutter", type: "Flying", power: 60, accuracy: 95, pp: 5 },
    { name: "Bite", type: "Dark", power: 60, accuracy: 100, pp: 5 },
    { name: "Wing Attack", type: "Flying", power: 60, accuracy: 100, pp: 6 },
    { name: "Confuse Ray", type: "Ghost", power: 0, accuracy: 100, pp: 10 },
  ],
  Oddish: [
    { name: "Absorb", type: "Grass", power: 20, accuracy: 100, pp: 10 },
    { name: "Acid", type: "Poison", power: 40, accuracy: 100, pp: 6 },
    { name: "Sleep Powder", type: "Grass", power: 0, accuracy: 75, pp: 3 },
    { name: "Stun Spore", type: "Grass", power: 0, accuracy: 75, pp: 4 },
  ],
  Gloom: [
    { name: "Acid", type: "Poison", power: 40, accuracy: 100, pp: 6 },
    { name: "Razor Leaf", type: "Grass", power: 55, accuracy: 95, pp: 6 },
    { name: "Stun Spore", type: "Grass", power: 0, accuracy: 75, pp: 4 },
    { name: "Sleep Powder", type: "Grass", power: 0, accuracy: 75, pp: 3 },
  ],
  Vileplume: [
    { name: "Petal Dance", type: "Grass", power: 70, accuracy: 100, pp: 5 },
    { name: "Acid", type: "Poison", power: 40, accuracy: 100, pp: 6 },
    { name: "Stun Spore", type: "Grass", power: 0, accuracy: 75, pp: 4 },
    { name: "Sleep Powder", type: "Grass", power: 0, accuracy: 75, pp: 3 },
  ],
  Paras: [
    { name: "Scratch", type: "Normal", power: 40, accuracy: 100, pp: 8 },
    { name: "Stun Spore", type: "Grass", power: 0, accuracy: 75, pp: 4 },
    { name: "Leech Life", type: "Bug", power: 20, accuracy: 100, pp: 5 },
    { name: "Poison Powder", type: "Poison", power: 0, accuracy: 75, pp: 4 },
  ],
  Parasect: [
    { name: "Slash", type: "Normal", power: 70, accuracy: 100, pp: 5 },
    { name: "Spore", type: "Grass", power: 0, accuracy: 100, pp: 3 },
    { name: "Leech Life", type: "Bug", power: 20, accuracy: 100, pp: 5 },
    { name: "Stun Spore", type: "Grass", power: 0, accuracy: 75, pp: 4 },
  ],
  Venonat: [
    { name: "Tackle", type: "Normal", power: 40, accuracy: 100, pp: 8 },
    { name: "Confusion", type: "Psychic", power: 50, accuracy: 100, pp: 5 },
    { name: "Stun Spore", type: "Grass", power: 0, accuracy: 75, pp: 4 },
    { name: "Leech Life", type: "Bug", power: 20, accuracy: 100, pp: 5 },
  ],
  Venomoth: [
    { name: "Confusion", type: "Psychic", power: 50, accuracy: 100, pp: 5 },
    { name: "Poison Powder", type: "Poison", power: 0, accuracy: 75, pp: 4 },
    { name: "Stun Spore", type: "Grass", power: 0, accuracy: 75, pp: 4 },
    { name: "Bug Bite", type: "Bug", power: 60, accuracy: 100, pp: 5 },
  ],
  Diglett: [
    { name: "Scratch", type: "Normal", power: 40, accuracy: 100, pp: 8 },
    { name: "Sand Attack", type: "Ground", power: 0, accuracy: 100, pp: 4 },
    { name: "Magnitude", type: "Ground", power: 70, accuracy: 100, pp: 5 },
    { name: "Dig", type: "Ground", power: 80, accuracy: 100, pp: 5 },
  ],
  Dugtrio: [
    { name: "Slash", type: "Normal", power: 70, accuracy: 100, pp: 5 },
    { name: "Earthquake", type: "Ground", power: 100, accuracy: 100, pp: 2 },
    { name: "Sand Attack", type: "Ground", power: 0, accuracy: 100, pp: 4 },
    { name: "Dig", type: "Ground", power: 80, accuracy: 100, pp: 5 },
  ],
  Meowth: [
    { name: "Scratch", type: "Normal", power: 40, accuracy: 100, pp: 8 },
    { name: "Bite", type: "Dark", power: 60, accuracy: 100, pp: 5 },
    { name: "Pay Day", type: "Normal", power: 40, accuracy: 100, pp: 10 },
    { name: "Fake Out", type: "Normal", power: 40, accuracy: 100, pp: 10 },
  ],
  Persian: [
    { name: "Slash", type: "Normal", power: 70, accuracy: 100, pp: 5 },
    { name: "Bite", type: "Dark", power: 60, accuracy: 100, pp: 5 },
    { name: "Faint Attack", type: "Dark", power: 60, accuracy: 100, pp: 10 },
    { name: "Fake Out", type: "Normal", power: 40, accuracy: 100, pp: 10 },
  ],
  Psyduck: [
    { name: "Water Gun", type: "Water", power: 40, accuracy: 100, pp: 6 },
    { name: "Confusion", type: "Psychic", power: 50, accuracy: 100, pp: 5 },
    { name: "Scratch", type: "Normal", power: 40, accuracy: 100, pp: 8 },
    { name: "Disable", type: "Normal", power: 0, accuracy: 100, pp: 5 },
  ],
  Golduck: [
    { name: "Hydro Pump", type: "Water", power: 110, accuracy: 80, pp: 2 },
    { name: "Psychic", type: "Psychic", power: 90, accuracy: 100, pp: 5 },
    { name: "Water Pulse", type: "Water", power: 60, accuracy: 100, pp: 8 },
    { name: "Aqua Tail", type: "Water", power: 90, accuracy: 90, pp: 5 },
  ],
  Mankey: [
    { name: "Scratch", type: "Normal", power: 40, accuracy: 100, pp: 8 },
    { name: "Karate Chop", type: "Fighting", power: 50, accuracy: 100, pp: 5 },
    { name: "Fury Swipes", type: "Normal", power: 18, accuracy: 80, pp: 10 },
    { name: "Seismic Toss", type: "Fighting", power: 0, accuracy: 100, pp: 5 },
  ],
  Primeape: [
    { name: "Karate Chop", type: "Fighting", power: 50, accuracy: 100, pp: 5 },
    { name: "Cross Chop", type: "Fighting", power: 100, accuracy: 80, pp: 3 },
    { name: "Thrash", type: "Normal", power: 90, accuracy: 100, pp: 3 },
    { name: "Focus Energy", type: "Normal", power: 0, accuracy: 100, pp: 3 },
  ],
  Growlithe: [
    { name: "Bite", type: "Dark", power: 60, accuracy: 100, pp: 5 },
    { name: "Flame Wheel", type: "Fire", power: 60, accuracy: 100, pp: 5 },
    { name: "Roar", type: "Normal", power: 0, accuracy: 100, pp: 5 },
    { name: "Ember", type: "Fire", power: 40, accuracy: 100, pp: 6 },
  ],
  Arcanine: [
    { name: "Flamethrower", type: "Fire", power: 90, accuracy: 100, pp: 4 },
    { name: "Bite", type: "Dark", power: 60, accuracy: 100, pp: 5 },
    { name: "Extreme Speed", type: "Normal", power: 80, accuracy: 100, pp: 5 },
    { name: "Fire Blast", type: "Fire", power: 110, accuracy: 85, pp: 3 },
  ],
  Poliwag: [
    { name: "Bubble", type: "Water", power: 40, accuracy: 100, pp: 6 },
    { name: "Water Gun", type: "Water", power: 40, accuracy: 100, pp: 6 },
    { name: "Hypnosis", type: "Psychic", power: 0, accuracy: 60, pp: 6 },
    { name: "Double Slap", type: "Normal", power: 15, accuracy: 85, pp: 5 },
  ],
  Poliwhirl: [
    { name: "Water Gun", type: "Water", power: 40, accuracy: 100, pp: 6 },
    { name: "Double Slap", type: "Normal", power: 15, accuracy: 85, pp: 5 },
    { name: "Hypnosis", type: "Psychic", power: 0, accuracy: 60, pp: 6 },
    { name: "Body Slam", type: "Normal", power: 85, accuracy: 100, pp: 5 },
  ],
  Poliwrath: [
    { name: "Hydro Pump", type: "Water", power: 110, accuracy: 80, pp: 2 },
    { name: "Body Slam", type: "Normal", power: 85, accuracy: 100, pp: 5 },
    { name: "Submission", type: "Fighting", power: 80, accuracy: 80, pp: 5 },
    { name: "Ice Punch", type: "Ice", power: 75, accuracy: 100, pp: 5 },
  ],
  Abra: [
    { name: "Teleport", type: "Psychic", power: 0, accuracy: 100, pp: 10 },
    { name: "Psychic", type: "Psychic", power: 90, accuracy: 100, pp: 5 },
    { name: "Psybeam", type: "Psychic", power: 65, accuracy: 100, pp: 10 },
    { name: "Recover", type: "Normal", power: 0, accuracy: 100, pp: 10 },
  ],
  Kadabra: [
    { name: "Psychic", type: "Psychic", power: 90, accuracy: 100, pp: 5 },
    { name: "Psybeam", type: "Psychic", power: 65, accuracy: 100, pp: 10 },
    { name: "Recover", type: "Normal", power: 0, accuracy: 100, pp: 10 },
    { name: "Future Sight", type: "Psychic", power: 120, accuracy: 100, pp: 3 },
  ],
  Alakazam: [
    { name: "Psychic", type: "Psychic", power: 90, accuracy: 100, pp: 5 },
    { name: "Psybeam", type: "Psychic", power: 65, accuracy: 100, pp: 10 },
    { name: "Shadow Ball", type: "Ghost", power: 80, accuracy: 100, pp: 5 },
    { name: "Recover", type: "Normal", power: 0, accuracy: 100, pp: 10 },
  ],
  Machop: [
    { name: "Karate Chop", type: "Fighting", power: 50, accuracy: 100, pp: 5 },
    { name: "Low Kick", type: "Fighting", power: 50, accuracy: 100, pp: 5 },
    { name: "Seismic Toss", type: "Fighting", power: 0, accuracy: 100, pp: 5 },
    { name: "Focus Energy", type: "Normal", power: 0, accuracy: 100, pp: 3 },
  ],
  Machoke: [
    { name: "Karate Chop", type: "Fighting", power: 50, accuracy: 100, pp: 5 },
    { name: "Submission", type: "Fighting", power: 80, accuracy: 80, pp: 5 },
    { name: "Seismic Toss", type: "Fighting", power: 0, accuracy: 100, pp: 5 },
    { name: "Low Kick", type: "Fighting", power: 50, accuracy: 100, pp: 5 },
  ],
  Machamp: [
    { name: "Cross Chop", type: "Fighting", power: 100, accuracy: 80, pp: 3 },
    { name: "Seismic Toss", type: "Fighting", power: 0, accuracy: 100, pp: 5 },
    { name: "Body Slam", type: "Normal", power: 85, accuracy: 100, pp: 5 },
    {
      name: "Dynamic Punch",
      type: "Fighting",
      power: 100,
      accuracy: 50,
      pp: 3,
    },
  ],
  Bellsprout: [
    { name: "Vine Whip", type: "Grass", power: 45, accuracy: 100, pp: 6 },
    { name: "Wrap", type: "Normal", power: 15, accuracy: 90, pp: 5 },
    { name: "Poison Powder", type: "Poison", power: 0, accuracy: 75, pp: 4 },
    { name: "Sleep Powder", type: "Grass", power: 0, accuracy: 75, pp: 3 },
  ],
  Weepinbell: [
    { name: "Vine Whip", type: "Grass", power: 45, accuracy: 100, pp: 6 },
    { name: "Acid", type: "Poison", power: 40, accuracy: 100, pp: 6 },
    { name: "Poison Powder", type: "Poison", power: 0, accuracy: 75, pp: 4 },
    { name: "Sleep Powder", type: "Grass", power: 0, accuracy: 75, pp: 3 },
  ],
  Victreebel: [
    { name: "Razor Leaf", type: "Grass", power: 55, accuracy: 95, pp: 6 },
    { name: "Acid", type: "Poison", power: 40, accuracy: 100, pp: 6 },
    { name: "Sleep Powder", type: "Grass", power: 0, accuracy: 75, pp: 3 },
    { name: "Stun Spore", type: "Grass", power: 0, accuracy: 75, pp: 4 },
  ],
  Tentacool: [
    { name: "Acid", type: "Poison", power: 40, accuracy: 100, pp: 6 },
    { name: "Water Gun", type: "Water", power: 40, accuracy: 100, pp: 6 },
    { name: "Wrap", type: "Normal", power: 15, accuracy: 90, pp: 5 },
    { name: "Poison Sting", type: "Poison", power: 15, accuracy: 100, pp: 8 },
  ],
  Tentacruel: [
    { name: "Acid", type: "Poison", power: 40, accuracy: 100, pp: 6 },
    { name: "Hydro Pump", type: "Water", power: 110, accuracy: 80, pp: 2 },
    { name: "Wrap", type: "Normal", power: 15, accuracy: 90, pp: 5 },
    { name: "Poison Sting", type: "Poison", power: 15, accuracy: 100, pp: 8 },
  ],
  Geodude: [
    { name: "Tackle", type: "Normal", power: 40, accuracy: 100, pp: 8 },
    { name: "Rock Throw", type: "Rock", power: 50, accuracy: 90, pp: 10 },
    { name: "Defense Curl", type: "Normal", power: 0, accuracy: 100, pp: 10 },
    { name: "Mud-Slap", type: "Ground", power: 20, accuracy: 100, pp: 10 },
  ],
  Graveler: [
    { name: "Rock Throw", type: "Rock", power: 50, accuracy: 90, pp: 10 },
    { name: "Earthquake", type: "Ground", power: 100, accuracy: 100, pp: 2 },
    { name: "Explosion", type: "Normal", power: 250, accuracy: 100, pp: 1 },
    { name: "Rollout", type: "Rock", power: 30, accuracy: 90, pp: 10 },
  ],
  Golem: [
    { name: "Rock Blast", type: "Rock", power: 25, accuracy: 90, pp: 10 },
    { name: "Earthquake", type: "Ground", power: 100, accuracy: 100, pp: 2 },
    { name: "Explosion", type: "Normal", power: 250, accuracy: 100, pp: 1 },
    { name: "Stone Edge", type: "Rock", power: 100, accuracy: 80, pp: 5 },
  ],
  Ponyta: [
    { name: "Ember", type: "Fire", power: 40, accuracy: 100, pp: 6 },
    { name: "Flame Wheel", type: "Fire", power: 60, accuracy: 100, pp: 5 },
    { name: "Stomp", type: "Normal", power: 65, accuracy: 100, pp: 10 },
    { name: "Growl", type: "Normal", power: 0, accuracy: 100, pp: 4 },
  ],
  Rapidash: [
    { name: "Flamethrower", type: "Fire", power: 90, accuracy: 100, pp: 4 },
    { name: "Fire Spin", type: "Fire", power: 35, accuracy: 85, pp: 5 },
    { name: "Stomp", type: "Normal", power: 65, accuracy: 100, pp: 10 },
    { name: "Agility", type: "Psychic", power: 0, accuracy: 100, pp: 3 },
  ],
  Slowpoke: [
    { name: "Water Gun", type: "Water", power: 40, accuracy: 100, pp: 6 },
    { name: "Confusion", type: "Psychic", power: 50, accuracy: 100, pp: 5 },
    { name: "Yawn", type: "Normal", power: 0, accuracy: 100, pp: 10 },
    { name: "Headbutt", type: "Normal", power: 70, accuracy: 100, pp: 10 },
  ],
  Slowbro: [
    { name: "Water Gun", type: "Water", power: 40, accuracy: 100, pp: 6 },
    { name: "Psychic", type: "Psychic", power: 90, accuracy: 100, pp: 5 },
    { name: "Amnesia", type: "Psychic", power: 0, accuracy: 100, pp: 10 },
    { name: "Confusion", type: "Psychic", power: 50, accuracy: 100, pp: 5 },
  ],
  Magnemite: [
    {
      name: "Thunder Shock",
      type: "Electric",
      power: 40,
      accuracy: 100,
      pp: 6,
    },
    { name: "Tackle", type: "Normal", power: 40, accuracy: 100, pp: 8 },
    { name: "Supersonic", type: "Normal", power: 0, accuracy: 55, pp: 5 },
    { name: "Screech", type: "Normal", power: 0, accuracy: 85, pp: 10 },
  ],
  Magneton: [
    { name: "Thunderbolt", type: "Electric", power: 90, accuracy: 100, pp: 5 },
    { name: "Zap Cannon", type: "Electric", power: 120, accuracy: 50, pp: 3 },
    { name: "Tackle", type: "Normal", power: 40, accuracy: 100, pp: 8 },
    { name: "Screech", type: "Normal", power: 0, accuracy: 85, pp: 10 },
  ],
  Farfetchd: [
    { name: "Slash", type: "Normal", power: 70, accuracy: 100, pp: 5 },
    { name: "Peck", type: "Flying", power: 35, accuracy: 100, pp: 6 },
    { name: "Fury Cutter", type: "Bug", power: 40, accuracy: 95, pp: 10 },
    { name: "Swords Dance", type: "Normal", power: 0, accuracy: 100, pp: 20 },
  ],
  Doduo: [
    { name: "Peck", type: "Flying", power: 35, accuracy: 100, pp: 6 },
    { name: "Fury Attack", type: "Normal", power: 15, accuracy: 85, pp: 6 },
    { name: "Quick Attack", type: "Normal", power: 40, accuracy: 100, pp: 6 },
    { name: "Growl", type: "Normal", power: 0, accuracy: 100, pp: 4 },
  ],
  Dodrio: [
    { name: "Tri Attack", type: "Normal", power: 80, accuracy: 100, pp: 10 },
    { name: "Drill Peck", type: "Flying", power: 80, accuracy: 100, pp: 5 },
    { name: "Agility", type: "Psychic", power: 0, accuracy: 100, pp: 3 },
    { name: "Fury Attack", type: "Normal", power: 15, accuracy: 85, pp: 6 },
  ],
  Seel: [
    { name: "Headbutt", type: "Normal", power: 70, accuracy: 100, pp: 10 },
    { name: "Water Gun", type: "Water", power: 40, accuracy: 100, pp: 6 },
    { name: "Growl", type: "Normal", power: 0, accuracy: 100, pp: 4 },
    { name: "Aurora Beam", type: "Ice", power: 65, accuracy: 100, pp: 10 },
  ],
  Dewgong: [
    { name: "Aurora Beam", type: "Ice", power: 65, accuracy: 100, pp: 10 },
    { name: "Ice Beam", type: "Ice", power: 90, accuracy: 100, pp: 5 },
    { name: "Water Gun", type: "Water", power: 40, accuracy: 100, pp: 6 },
    { name: "Headbutt", type: "Normal", power: 70, accuracy: 100, pp: 10 },
  ],
  Grimer: [
    { name: "Sludge", type: "Poison", power: 65, accuracy: 100, pp: 10 },
    { name: "Pound", type: "Normal", power: 40, accuracy: 100, pp: 8 },
    { name: "Mud-Slap", type: "Ground", power: 20, accuracy: 100, pp: 10 },
    { name: "Harden", type: "Normal", power: 0, accuracy: 100, pp: 6 },
  ],
  Muk: [
    { name: "Sludge Bomb", type: "Poison", power: 90, accuracy: 100, pp: 5 },
    { name: "Acid Armor", type: "Poison", power: 0, accuracy: 100, pp: 20 },
    { name: "Pound", type: "Normal", power: 40, accuracy: 100, pp: 8 },
    { name: "Harden", type: "Normal", power: 0, accuracy: 100, pp: 6 },
  ],
  Shellder: [
    { name: "Tackle", type: "Normal", power: 40, accuracy: 100, pp: 8 },
    { name: "Clamp", type: "Water", power: 35, accuracy: 85, pp: 10 },
    { name: "Icicle Spear", type: "Ice", power: 25, accuracy: 100, pp: 15 },
    { name: "Aurora Beam", type: "Ice", power: 65, accuracy: 100, pp: 10 },
  ],
  Cloyster: [
    { name: "Icicle Spear", type: "Ice", power: 25, accuracy: 100, pp: 15 },
    { name: "Ice Beam", type: "Ice", power: 90, accuracy: 100, pp: 5 },
    { name: "Clamp", type: "Water", power: 35, accuracy: 85, pp: 10 },
    { name: "Aurora Beam", type: "Ice", power: 65, accuracy: 100, pp: 10 },
  ],
  Gastly: [
    { name: "Lick", type: "Ghost", power: 30, accuracy: 100, pp: 10 },
    { name: "Night Shade", type: "Ghost", power: 0, accuracy: 100, pp: 15 },
    { name: "Confuse Ray", type: "Ghost", power: 0, accuracy: 100, pp: 10 },
    { name: "Curse", type: "Ghost", power: 0, accuracy: 100, pp: 10 },
  ],
  Haunter: [
    { name: "Shadow Ball", type: "Ghost", power: 80, accuracy: 100, pp: 5 },
    { name: "Night Shade", type: "Ghost", power: 0, accuracy: 100, pp: 15 },
    { name: "Confuse Ray", type: "Ghost", power: 0, accuracy: 100, pp: 10 },
    { name: "Curse", type: "Ghost", power: 0, accuracy: 100, pp: 10 },
  ],
  Gengar: [
    { name: "Shadow Ball", type: "Ghost", power: 80, accuracy: 100, pp: 5 },
    { name: "Dark Pulse", type: "Dark", power: 80, accuracy: 100, pp: 5 },
    { name: "Night Shade", type: "Ghost", power: 0, accuracy: 100, pp: 15 },
    { name: "Curse", type: "Ghost", power: 0, accuracy: 100, pp: 10 },
  ],
  Onix: [
    { name: "Rock Throw", type: "Rock", power: 50, accuracy: 90, pp: 10 },
    { name: "Tackle", type: "Normal", power: 40, accuracy: 100, pp: 8 },
    { name: "Bind", type: "Normal", power: 15, accuracy: 85, pp: 20 },
    { name: "Rock Slide", type: "Rock", power: 75, accuracy: 90, pp: 10 },
  ],
  Drowzee: [
    { name: "Psybeam", type: "Psychic", power: 65, accuracy: 100, pp: 10 },
    { name: "Confusion", type: "Psychic", power: 50, accuracy: 100, pp: 5 },
    { name: "Hypnosis", type: "Psychic", power: 0, accuracy: 60, pp: 6 },
    { name: "Headbutt", type: "Normal", power: 70, accuracy: 100, pp: 10 },
  ],
  Hypno: [
    { name: "Psychic", type: "Psychic", power: 90, accuracy: 100, pp: 5 },
    { name: "Psybeam", type: "Psychic", power: 65, accuracy: 100, pp: 10 },
    { name: "Hypnosis", type: "Psychic", power: 0, accuracy: 60, pp: 6 },
    { name: "Confusion", type: "Psychic", power: 50, accuracy: 100, pp: 5 },
  ],
  Krabby: [
    { name: "Bubble", type: "Water", power: 40, accuracy: 100, pp: 6 },
    { name: "Vice Grip", type: "Normal", power: 55, accuracy: 100, pp: 10 },
    { name: "Leer", type: "Normal", power: 0, accuracy: 100, pp: 4 },
    { name: "Mud Shot", type: "Ground", power: 55, accuracy: 95, pp: 10 },
  ],
  Kingler: [
    { name: "Crabhammer", type: "Water", power: 90, accuracy: 90, pp: 5 },
    { name: "Vice Grip", type: "Normal", power: 55, accuracy: 100, pp: 10 },
    { name: "Leer", type: "Normal", power: 0, accuracy: 100, pp: 4 },
    { name: "Slash", type: "Normal", power: 70, accuracy: 100, pp: 5 },
  ],
  Voltorb: [
    { name: "Tackle", type: "Normal", power: 40, accuracy: 100, pp: 8 },
    { name: "Screech", type: "Normal", power: 0, accuracy: 85, pp: 10 },
    { name: "Spark", type: "Electric", power: 65, accuracy: 100, pp: 10 },
    { name: "Self-Destruct", type: "Normal", power: 200, accuracy: 100, pp: 1 },
  ],
  Electrode: [
    { name: "Tackle", type: "Normal", power: 40, accuracy: 100, pp: 8 },
    { name: "Screech", type: "Normal", power: 0, accuracy: 85, pp: 10 },
    { name: "Spark", type: "Electric", power: 65, accuracy: 100, pp: 10 },
    { name: "Self-Destruct", type: "Normal", power: 200, accuracy: 100, pp: 1 },
  ],
  Exeggcute: [
    { name: "Barrage", type: "Psychic", power: 15, accuracy: 85, pp: 10 },
    { name: "Hypnosis", type: "Psychic", power: 0, accuracy: 60, pp: 6 },
    { name: "Confusion", type: "Psychic", power: 50, accuracy: 100, pp: 5 },
    { name: "Leech Seed", type: "Grass", power: 0, accuracy: 90, pp: 3 },
  ],
  Exeggutor: [
    { name: "Psychic", type: "Psychic", power: 90, accuracy: 100, pp: 5 },
    { name: "Seed Bomb", type: "Grass", power: 80, accuracy: 100, pp: 5 },
    { name: "Stomp", type: "Normal", power: 65, accuracy: 100, pp: 10 },
    { name: "Sleep Powder", type: "Grass", power: 0, accuracy: 75, pp: 3 },
  ],
  Cubone: [
    { name: "Bone Club", type: "Ground", power: 65, accuracy: 85, pp: 10 },
    { name: "Headbutt", type: "Normal", power: 70, accuracy: 100, pp: 10 },
    { name: "Leer", type: "Normal", power: 0, accuracy: 100, pp: 4 },
    { name: "Tail Whip", type: "Normal", power: 0, accuracy: 100, pp: 4 },
  ],
  Marowak: [
    { name: "Bonemerang", type: "Ground", power: 50, accuracy: 90, pp: 10 },
    { name: "Headbutt", type: "Normal", power: 70, accuracy: 100, pp: 10 },
    { name: "Retaliate", type: "Normal", power: 70, accuracy: 100, pp: 5 },
    { name: "Bone Club", type: "Ground", power: 65, accuracy: 85, pp: 10 },
  ],
  Hitmonlee: [
    {
      name: "High Jump Kick",
      type: "Fighting",
      power: 130,
      accuracy: 90,
      pp: 5,
    },
    { name: "Jump Kick", type: "Fighting", power: 70, accuracy: 95, pp: 10 },
    { name: "Double Kick", type: "Fighting", power: 30, accuracy: 100, pp: 5 },
    { name: "Counter", type: "Fighting", power: 0, accuracy: 100, pp: 20 },
  ],
  Hitmonchan: [
    { name: "Fire Punch", type: "Fire", power: 75, accuracy: 100, pp: 15 },
    { name: "Ice Punch", type: "Ice", power: 75, accuracy: 100, pp: 15 },
    {
      name: "Thunder Punch",
      type: "Electric",
      power: 75,
      accuracy: 100,
      pp: 15,
    },
    { name: "Mach Punch", type: "Fighting", power: 40, accuracy: 100, pp: 10 },
  ],
  Lickitung: [
    { name: "Lick", type: "Ghost", power: 30, accuracy: 100, pp: 10 },
    { name: "Stomp", type: "Normal", power: 65, accuracy: 100, pp: 10 },
    { name: "Slam", type: "Normal", power: 80, accuracy: 75, pp: 10 },
    { name: "Wrap", type: "Normal", power: 15, accuracy: 90, pp: 5 },
  ],
  Koffing: [
    { name: "Tackle", type: "Normal", power: 40, accuracy: 100, pp: 8 },
    { name: "Smokescreen", type: "Normal", power: 0, accuracy: 100, pp: 4 },
    { name: "Sludge", type: "Poison", power: 65, accuracy: 100, pp: 10 },
    { name: "Self-Destruct", type: "Normal", power: 200, accuracy: 100, pp: 1 },
  ],
  Weezing: [
    { name: "Tackle", type: "Normal", power: 40, accuracy: 100, pp: 8 },
    { name: "Sludge Bomb", type: "Poison", power: 90, accuracy: 100, pp: 5 },
    { name: "Smokescreen", type: "Normal", power: 0, accuracy: 100, pp: 4 },
    { name: "Explosion", type: "Normal", power: 250, accuracy: 100, pp: 1 },
  ],
  Rhyhorn: [
    { name: "Horn Attack", type: "Normal", power: 65, accuracy: 100, pp: 5 },
    { name: "Stomp", type: "Normal", power: 65, accuracy: 100, pp: 10 },
    { name: "Rock Blast", type: "Rock", power: 25, accuracy: 90, pp: 10 },
    { name: "Take Down", type: "Normal", power: 90, accuracy: 85, pp: 10 },
  ],
  Rhydon: [
    { name: "Horn Drill", type: "Normal", power: 0, accuracy: 30, pp: 5 },
    { name: "Earthquake", type: "Ground", power: 100, accuracy: 100, pp: 2 },
    { name: "Rock Slide", type: "Rock", power: 75, accuracy: 90, pp: 10 },
    { name: "Stomp", type: "Normal", power: 65, accuracy: 100, pp: 10 },
  ],
  Chansey: [
    { name: "Pound", type: "Normal", power: 40, accuracy: 100, pp: 8 },
    { name: "Double-Edge", type: "Normal", power: 120, accuracy: 100, pp: 3 },
    { name: "Soft-Boiled", type: "Normal", power: 0, accuracy: 100, pp: 10 },
    { name: "Sing", type: "Normal", power: 0, accuracy: 55, pp: 3 },
  ],
  Tangela: [
    { name: "Vine Whip", type: "Grass", power: 45, accuracy: 100, pp: 6 },
    { name: "Bind", type: "Normal", power: 15, accuracy: 85, pp: 20 },
    { name: "Sleep Powder", type: "Grass", power: 0, accuracy: 75, pp: 3 },
    { name: "Poison Powder", type: "Poison", power: 0, accuracy: 75, pp: 4 },
  ],
  Kangaskhan: [
    { name: "Comet Punch", type: "Normal", power: 18, accuracy: 85, pp: 15 },
    { name: "Headbutt", type: "Normal", power: 70, accuracy: 100, pp: 10 },
    { name: "Mega Punch", type: "Normal", power: 80, accuracy: 85, pp: 20 },
    { name: "Counter", type: "Fighting", power: 0, accuracy: 100, pp: 20 },
  ],
  Horsea: [
    { name: "Bubble", type: "Water", power: 40, accuracy: 100, pp: 6 },
    { name: "Smokescreen", type: "Normal", power: 0, accuracy: 100, pp: 4 },
    { name: "Leer", type: "Normal", power: 0, accuracy: 100, pp: 4 },
    { name: "Water Gun", type: "Water", power: 40, accuracy: 100, pp: 6 },
  ],
  Seadra: [
    { name: "Water Gun", type: "Water", power: 40, accuracy: 100, pp: 6 },
    { name: "Agility", type: "Psychic", power: 0, accuracy: 100, pp: 3 },
    { name: "Dragon Breath", type: "Dragon", power: 60, accuracy: 100, pp: 10 },
    { name: "Leer", type: "Normal", power: 0, accuracy: 100, pp: 4 },
  ],
  Goldeen: [
    { name: "Peck", type: "Flying", power: 35, accuracy: 100, pp: 6 },
    { name: "Horn Attack", type: "Normal", power: 65, accuracy: 100, pp: 5 },
    { name: "Water Gun", type: "Water", power: 40, accuracy: 100, pp: 6 },
    { name: "Agility", type: "Psychic", power: 0, accuracy: 100, pp: 3 },
  ],
  Seaking: [
    { name: "Horn Attack", type: "Normal", power: 65, accuracy: 100, pp: 5 },
    { name: "Waterfall", type: "Water", power: 80, accuracy: 100, pp: 10 },
    { name: "Fury Attack", type: "Normal", power: 15, accuracy: 85, pp: 6 },
    { name: "Agility", type: "Psychic", power: 0, accuracy: 100, pp: 3 },
  ],
  Staryu: [
    { name: "Tackle", type: "Normal", power: 40, accuracy: 100, pp: 8 },
    { name: "Water Gun", type: "Water", power: 40, accuracy: 100, pp: 6 },
    { name: "Rapid Spin", type: "Normal", power: 50, accuracy: 100, pp: 5 },
    { name: "Recover", type: "Normal", power: 0, accuracy: 100, pp: 10 },
  ],
  Starmie: [
    { name: "Water Gun", type: "Water", power: 40, accuracy: 100, pp: 6 },
    { name: "Psychic", type: "Psychic", power: 90, accuracy: 100, pp: 5 },
    { name: "Rapid Spin", type: "Normal", power: 50, accuracy: 100, pp: 5 },
    { name: "Recover", type: "Normal", power: 0, accuracy: 100, pp: 10 },
  ],
  MrMime: [
    { name: "Confusion", type: "Psychic", power: 50, accuracy: 100, pp: 5 },
    { name: "Double Slap", type: "Normal", power: 15, accuracy: 85, pp: 5 },
    { name: "Barrier", type: "Psychic", power: 0, accuracy: 100, pp: 20 },
    { name: "Reflect", type: "Psychic", power: 0, accuracy: 100, pp: 20 },
  ],
  Scyther: [
    { name: "Quick Attack", type: "Normal", power: 40, accuracy: 100, pp: 6 },
    { name: "Fury Cutter", type: "Bug", power: 40, accuracy: 95, pp: 10 },
    { name: "Wing Attack", type: "Flying", power: 60, accuracy: 100, pp: 6 },
    { name: "Slash", type: "Normal", power: 70, accuracy: 100, pp: 5 },
  ],
  Jynx: [
    { name: "Pound", type: "Normal", power: 40, accuracy: 100, pp: 8 },
    { name: "Lovely Kiss", type: "Normal", power: 0, accuracy: 75, pp: 5 },
    { name: "Ice Punch", type: "Ice", power: 75, accuracy: 100, pp: 15 },
    { name: "Psychic", type: "Psychic", power: 90, accuracy: 100, pp: 5 },
  ],
  Electabuzz: [
    {
      name: "Thunder Punch",
      type: "Electric",
      power: 75,
      accuracy: 100,
      pp: 15,
    },
    { name: "Quick Attack", type: "Normal", power: 40, accuracy: 100, pp: 6 },
    {
      name: "Thunder Shock",
      type: "Electric",
      power: 40,
      accuracy: 100,
      pp: 6,
    },
    { name: "Swift", type: "Normal", power: 60, accuracy: 100, pp: 20 },
  ],
  Magmar: [
    { name: "Ember", type: "Fire", power: 40, accuracy: 100, pp: 6 },
    { name: "Confuse Ray", type: "Ghost", power: 0, accuracy: 100, pp: 10 },
    { name: "Smokescreen", type: "Normal", power: 0, accuracy: 100, pp: 4 },
    { name: "Flamethrower", type: "Fire", power: 90, accuracy: 100, pp: 4 },
  ],
  Pinsir: [
    { name: "Vice Grip", type: "Normal", power: 55, accuracy: 100, pp: 10 },
    { name: "Seismic Toss", type: "Fighting", power: 60, accuracy: 100, pp: 5 },
    { name: "Harden", type: "Normal", power: 0, accuracy: 100, pp: 6 },
    { name: "Revenge", type: "Normal", power: 60, accuracy: 100, pp: 5 },
  ],
  Tauros: [
    { name: "Tackle", type: "Normal", power: 40, accuracy: 100, pp: 8 },
    { name: "Stomp", type: "Normal", power: 65, accuracy: 100, pp: 10 },
    { name: "Horn Attack", type: "Normal", power: 65, accuracy: 100, pp: 5 },
    { name: "Take Down", type: "Normal", power: 90, accuracy: 85, pp: 10 },
  ],
  Magikarp: [
    { name: "Splash", type: "Normal", power: 0, accuracy: 100, pp: 40 },
    { name: "Tackle", type: "Normal", power: 40, accuracy: 100, pp: 8 },
    { name: "Flail", type: "Normal", power: 0, accuracy: 100, pp: 10 },
    { name: "Bounce", type: "Flying", power: 85, accuracy: 85, pp: 5 },
  ],
  Gyarados: [
    { name: "Bite", type: "Dark", power: 60, accuracy: 100, pp: 5 },
    { name: "Hydro Pump", type: "Water", power: 110, accuracy: 80, pp: 2 },
    { name: "Dragon Dance", type: "Dragon", power: 0, accuracy: 100, pp: 10 },
    { name: "Hyper Beam", type: "Normal", power: 150, accuracy: 90, pp: 1 },
  ],
  Lapras: [
    { name: "Water Gun", type: "Water", power: 40, accuracy: 100, pp: 6 },
    { name: "Body Slam", type: "Normal", power: 85, accuracy: 100, pp: 5 },
    { name: "Ice Beam", type: "Ice", power: 90, accuracy: 100, pp: 5 },
    { name: "Surf", type: "Water", power: 90, accuracy: 100, pp: 3 },
  ],
  Ditto: [
    { name: "Transform", type: "Normal", power: 0, accuracy: 100, pp: 10 },
    { name: "Struggle", type: "Normal", power: 50, accuracy: 100, pp: 1 },
    { name: "Splash", type: "Normal", power: 0, accuracy: 100, pp: 40 },
    { name: "Acid", type: "Poison", power: 40, accuracy: 100, pp: 6 },
  ],
  Eevee: [
    { name: "Tackle", type: "Normal", power: 40, accuracy: 100, pp: 8 },
    { name: "Quick Attack", type: "Normal", power: 40, accuracy: 100, pp: 6 },
    { name: "Bite", type: "Dark", power: 60, accuracy: 100, pp: 5 },
    { name: "Swift", type: "Normal", power: 60, accuracy: 100, pp: 20 },
  ],
  Vaporeon: [
    { name: "Water Gun", type: "Water", power: 40, accuracy: 100, pp: 6 },
    { name: "Aqua Tail", type: "Water", power: 90, accuracy: 90, pp: 5 },
    { name: "Bite", type: "Dark", power: 60, accuracy: 100, pp: 5 },
    { name: "Hydro Pump", type: "Water", power: 110, accuracy: 80, pp: 2 },
  ],
  Jolteon: [
    {
      name: "Thunder Shock",
      type: "Electric",
      power: 40,
      accuracy: 100,
      pp: 6,
    },
    { name: "Pin Missile", type: "Bug", power: 25, accuracy: 95, pp: 20 },
    { name: "Quick Attack", type: "Normal", power: 40, accuracy: 100, pp: 6 },
    { name: "Thunderbolt", type: "Electric", power: 90, accuracy: 100, pp: 5 },
  ],
  Flareon: [
    { name: "Ember", type: "Fire", power: 40, accuracy: 100, pp: 6 },
    { name: "Flame Charge", type: "Fire", power: 50, accuracy: 100, pp: 20 },
    { name: "Bite", type: "Dark", power: 60, accuracy: 100, pp: 5 },
    { name: "Flamethrower", type: "Fire", power: 90, accuracy: 100, pp: 4 },
  ],
  Porygon: [
    { name: "Tackle", type: "Normal", power: 40, accuracy: 100, pp: 8 },
    { name: "Sharpen", type: "Normal", power: 0, accuracy: 100, pp: 10 },
    { name: "Psybeam", type: "Psychic", power: 65, accuracy: 100, pp: 10 },
    { name: "Conversion", type: "Normal", power: 0, accuracy: 100, pp: 30 },
  ],
  Omanyte: [
    { name: "Scratch", type: "Normal", power: 40, accuracy: 100, pp: 8 },
    { name: "Water Gun", type: "Water", power: 40, accuracy: 100, pp: 6 },
    { name: "Bite", type: "Dark", power: 60, accuracy: 100, pp: 5 },
    { name: "Rock Blast", type: "Rock", power: 25, accuracy: 90, pp: 10 },
  ],
  Omastar: [
    { name: "Hydro Pump", type: "Water", power: 110, accuracy: 80, pp: 2 },
    { name: "Rock Blast", type: "Rock", power: 25, accuracy: 90, pp: 10 },
    { name: "Bite", type: "Dark", power: 60, accuracy: 100, pp: 5 },
    { name: "Surf", type: "Water", power: 90, accuracy: 100, pp: 3 },
  ],
  Kabuto: [
    { name: "Scratch", type: "Normal", power: 40, accuracy: 100, pp: 8 },
    { name: "Absorb", type: "Grass", power: 20, accuracy: 100, pp: 10 },
    { name: "Harden", type: "Normal", power: 0, accuracy: 100, pp: 6 },
    { name: "Water Gun", type: "Water", power: 40, accuracy: 100, pp: 6 },
  ],
  Kabutops: [
    { name: "Slash", type: "Normal", power: 70, accuracy: 100, pp: 5 },
    { name: "Waterfall", type: "Water", power: 80, accuracy: 100, pp: 10 },
    { name: "Aqua Jet", type: "Water", power: 40, accuracy: 100, pp: 20 },
    { name: "Absorb", type: "Grass", power: 20, accuracy: 100, pp: 10 },
  ],
  Aerodactyl: [
    { name: "Wing Attack", type: "Flying", power: 60, accuracy: 100, pp: 6 },
    { name: "Rock Slide", type: "Rock", power: 75, accuracy: 90, pp: 10 },
    { name: "Crunch", type: "Dark", power: 80, accuracy: 100, pp: 10 },
    { name: "Hyper Beam", type: "Normal", power: 150, accuracy: 90, pp: 1 },
  ],
  Snorlax: [
    { name: "Body Slam", type: "Normal", power: 85, accuracy: 100, pp: 5 },
    { name: "Rest", type: "Psychic", power: 0, accuracy: 100, pp: 10 },
    { name: "Hyper Beam", type: "Normal", power: 150, accuracy: 90, pp: 1 },
    { name: "Crunch", type: "Dark", power: 80, accuracy: 100, pp: 10 },
  ],
  Articuno: [
    { name: "Ice Beam", type: "Ice", power: 90, accuracy: 100, pp: 5 },
    { name: "Blizzard", type: "Ice", power: 110, accuracy: 70, pp: 5 },
    { name: "Agility", type: "Psychic", power: 0, accuracy: 100, pp: 3 },
    { name: "Peck", type: "Flying", power: 35, accuracy: 100, pp: 6 },
  ],
  Zapdos: [
    {
      name: "Thunder Shock",
      type: "Electric",
      power: 40,
      accuracy: 100,
      pp: 6,
    },
    { name: "Drill Peck", type: "Flying", power: 80, accuracy: 100, pp: 5 },
    { name: "Agility", type: "Psychic", power: 0, accuracy: 100, pp: 3 },
    { name: "Thunderbolt", type: "Electric", power: 90, accuracy: 100, pp: 5 },
  ],
  Moltres: [
    { name: "Fire Spin", type: "Fire", power: 35, accuracy: 85, pp: 5 },
    { name: "Flamethrower", type: "Fire", power: 90, accuracy: 100, pp: 4 },
    { name: "Agility", type: "Psychic", power: 0, accuracy: 100, pp: 3 },
    { name: "Peck", type: "Flying", power: 35, accuracy: 100, pp: 6 },
  ],
  Dratini: [
    { name: "Wrap", type: "Normal", power: 15, accuracy: 90, pp: 5 },
    { name: "Leer", type: "Normal", power: 0, accuracy: 100, pp: 4 },
    { name: "Dragon Rage", type: "Dragon", power: 40, accuracy: 100, pp: 10 },
    { name: "Twister", type: "Dragon", power: 40, accuracy: 100, pp: 10 },
  ],
  Dragonair: [
    { name: "Dragon Tail", type: "Dragon", power: 60, accuracy: 90, pp: 10 },
    { name: "Wrap", type: "Normal", power: 15, accuracy: 90, pp: 5 },
    { name: "Dragon Rage", type: "Dragon", power: 40, accuracy: 100, pp: 10 },
    { name: "Agility", type: "Psychic", power: 0, accuracy: 100, pp: 3 },
  ],
  Dragonite: [
    { name: "Dragon Claw", type: "Dragon", power: 80, accuracy: 100, pp: 10 },
    { name: "Hyper Beam", type: "Normal", power: 150, accuracy: 90, pp: 1 },
    { name: "Wing Attack", type: "Flying", power: 60, accuracy: 100, pp: 6 },
    {
      name: "Thunder Punch",
      type: "Electric",
      power: 75,
      accuracy: 100,
      pp: 15,
    },
  ],
  Mewtwo: [
    { name: "Psychic", type: "Psychic", power: 90, accuracy: 100, pp: 5 },
    { name: "Shadow Ball", type: "Ghost", power: 80, accuracy: 100, pp: 5 },
    { name: "Barrier", type: "Psychic", power: 0, accuracy: 100, pp: 20 },
    { name: "Recover", type: "Normal", power: 0, accuracy: 100, pp: 10 },
  ],
  Mew: [
    { name: "Psychic", type: "Psychic", power: 90, accuracy: 100, pp: 5 },
    { name: "Pound", type: "Normal", power: 40, accuracy: 100, pp: 8 },
    { name: "Transform", type: "Normal", power: 0, accuracy: 100, pp: 10 },
    { name: "Ancient Power", type: "Rock", power: 60, accuracy: 100, pp: 5 },
  ],
};
